INSERT INTO CATEGORIAS(ID, NOME)
VALUES
(NEWID(), 'ALIMENTOS'),
(NEWID(), 'BEBIDAS'),
(NEWID(), 'SAÚDE E BELEZA'),
(NEWID(), 'ELETRODOMÉSTICOS'),
(NEWID(), 'CAMA, MESA E BANHO'),
(NEWID(), 'AUTOMOTIVO'),
(NEWID(), 'ESPORTES E LAZER'),
(NEWID(), 'LIMPEZA');

SELECT * FROM CATEGORIAS
ORDER BY NOME ASC;